version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongodb
      - rabbitmq
    volumes:
      - auth_node_modules:/app/node_modules
    networks:
      - microservices-network
    restart: unless-stopped

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./product-service/.env
    depends_on:
      - mongodb
      - rabbitmq
      - auth-service
    volumes:
      - product_node_modules:/app/node_modules
    networks:
      - microservices-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ messaging
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices-network
    restart: unless-stopped

volumes:
  mongodb_data:
  rabbitmq_data:
  auth_node_modules:
  product_node_modules:

networks:
  microservices-network:
    driver: bridge
